# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import metadata_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='search.proto',
  package='spotify.search.proto',
  serialized_pb=_b('\n\x0csearch.proto\x12\x14spotify.search.proto\x1a\x0emetadata.proto\"\xb7\x01\n\rSearchRequest\x12\r\n\x05query\x18\x01 \x01(\t\x12\x36\n\x04type\x18\x02 \x01(\x0e\x32(.spotify.search.proto.SearchRequest.Type\x12\r\n\x05limit\x18\x03 \x01(\x05\x12\x0e\n\x06offset\x18\x04 \x01(\x05\"@\n\x04Type\x12\t\n\x05TRACK\x10\x00\x12\t\n\x05\x41LBUM\x10\x01\x12\n\n\x06\x41RTIST\x10\x02\x12\x0c\n\x08PLAYLIST\x10\x03\x12\x08\n\x04USER\x10\x04\"S\n\x08Playlist\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12,\n\x05image\x18\x03 \x01(\x0b\x32\x1d.spotify.metadata.proto.Image\"l\n\x04User\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x11\n\tfull_name\x18\x02 \x01(\t\x12,\n\x05image\x18\x03 \x01(\x0b\x32\x1d.spotify.metadata.proto.Image\x12\x11\n\tfollowers\x18\x04 \x01(\x11\"\x99\x02\n\x0bSearchReply\x12\x0c\n\x04hits\x18\x01 \x01(\x11\x12,\n\x05track\x18\x02 \x03(\x0b\x32\x1d.spotify.metadata.proto.Track\x12,\n\x05\x61lbum\x18\x03 \x03(\x0b\x32\x1d.spotify.metadata.proto.Album\x12.\n\x06\x61rtist\x18\x04 \x03(\x0b\x32\x1e.spotify.metadata.proto.Artist\x12\x30\n\x08playlist\x18\x05 \x03(\x0b\x32\x1e.spotify.search.proto.Playlist\x12\x14\n\x0c\x64id_you_mean\x18\x06 \x01(\t\x12(\n\x04user\x18\x07 \x03(\x0b\x32\x1a.spotify.search.proto.User')
  ,
  dependencies=[metadata_pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_SEARCHREQUEST_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='spotify.search.proto.SearchRequest.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRACK', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ALBUM', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ARTIST', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PLAYLIST', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='USER', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=174,
  serialized_end=238,
)
_sym_db.RegisterEnumDescriptor(_SEARCHREQUEST_TYPE)


_SEARCHREQUEST = _descriptor.Descriptor(
  name='SearchRequest',
  full_name='spotify.search.proto.SearchRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='spotify.search.proto.SearchRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='type', full_name='spotify.search.proto.SearchRequest.type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limit', full_name='spotify.search.proto.SearchRequest.limit', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset', full_name='spotify.search.proto.SearchRequest.offset', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SEARCHREQUEST_TYPE,
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=238,
)


_PLAYLIST = _descriptor.Descriptor(
  name='Playlist',
  full_name='spotify.search.proto.Playlist',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='spotify.search.proto.Playlist.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='spotify.search.proto.Playlist.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='spotify.search.proto.Playlist.image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=240,
  serialized_end=323,
)


_USER = _descriptor.Descriptor(
  name='User',
  full_name='spotify.search.proto.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='username', full_name='spotify.search.proto.User.username', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='full_name', full_name='spotify.search.proto.User.full_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='image', full_name='spotify.search.proto.User.image', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='followers', full_name='spotify.search.proto.User.followers', index=3,
      number=4, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=325,
  serialized_end=433,
)


_SEARCHREPLY = _descriptor.Descriptor(
  name='SearchReply',
  full_name='spotify.search.proto.SearchReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hits', full_name='spotify.search.proto.SearchReply.hits', index=0,
      number=1, type=17, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='track', full_name='spotify.search.proto.SearchReply.track', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='album', full_name='spotify.search.proto.SearchReply.album', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='artist', full_name='spotify.search.proto.SearchReply.artist', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playlist', full_name='spotify.search.proto.SearchReply.playlist', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='did_you_mean', full_name='spotify.search.proto.SearchReply.did_you_mean', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='user', full_name='spotify.search.proto.SearchReply.user', index=6,
      number=7, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=436,
  serialized_end=717,
)

_SEARCHREQUEST.fields_by_name['type'].enum_type = _SEARCHREQUEST_TYPE
_SEARCHREQUEST_TYPE.containing_type = _SEARCHREQUEST
_PLAYLIST.fields_by_name['image'].message_type = metadata_pb2._IMAGE
_USER.fields_by_name['image'].message_type = metadata_pb2._IMAGE
_SEARCHREPLY.fields_by_name['track'].message_type = metadata_pb2._TRACK
_SEARCHREPLY.fields_by_name['album'].message_type = metadata_pb2._ALBUM
_SEARCHREPLY.fields_by_name['artist'].message_type = metadata_pb2._ARTIST
_SEARCHREPLY.fields_by_name['playlist'].message_type = _PLAYLIST
_SEARCHREPLY.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['SearchRequest'] = _SEARCHREQUEST
DESCRIPTOR.message_types_by_name['Playlist'] = _PLAYLIST
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['SearchReply'] = _SEARCHREPLY

SearchRequest = _reflection.GeneratedProtocolMessageType('SearchRequest', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHREQUEST,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:spotify.search.proto.SearchRequest)
  ))
_sym_db.RegisterMessage(SearchRequest)

Playlist = _reflection.GeneratedProtocolMessageType('Playlist', (_message.Message,), dict(
  DESCRIPTOR = _PLAYLIST,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:spotify.search.proto.Playlist)
  ))
_sym_db.RegisterMessage(Playlist)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:spotify.search.proto.User)
  ))
_sym_db.RegisterMessage(User)

SearchReply = _reflection.GeneratedProtocolMessageType('SearchReply', (_message.Message,), dict(
  DESCRIPTOR = _SEARCHREPLY,
  __module__ = 'search_pb2'
  # @@protoc_insertion_point(class_scope:spotify.search.proto.SearchReply)
  ))
_sym_db.RegisterMessage(SearchReply)


# @@protoc_insertion_point(module_scope)
